### ISSUE TITLE
create a bottled version in homebrew/science

### ISSUE THREAD

**Issue by ginolhac** [MikkelSchubert/adapterremoval#1]
that would great to to be able to use `brew install adapterremoval` and get updates

**Comment by tseemann** [comment]
@ginolhac I am working on it :arrow_right: https://github.com/Homebrew/homebrew-science/pull/3307

**Comment by MikkelSchubert** [comment]
Thank you for doing this.
Just let me know if I need to change anything to make life easier for you.

**Comment by ginolhac** [comment]
thanks a lot @tseemann !

**Comment by mgajdeczka** [comment]
Not rushing you @tseemann, just wondering if you have an estimated date for inclusion into Homebrew? Happy to see it being added!

**Comment by MikkelSchubert** [comment]
AdapterRemoval is now available in homebrew-science:
https://github.com/Homebrew/homebrew-science/pull/3433
