### ISSUE TITLE
Several spelling errors

### ISSUE THREAD

**Issue by tillea** [MikkelSchubert/adapterremoval#13]
Hi,
when packaging the recent version for Debian our policy checker spotted some spelling errors.  Find a [patch here](https://anonscm.debian.org/cgit/debian-med/adapterremoval.git/tree/debian/patches/spelling.patch) to fix these typos.
Hope this helps, Andreas.

**Comment by MikkelSchubert** [comment]
Thank you very much!
I've applied your patch so that it'll be included in the next release (whenever that is).
