### ISSUE TITLE
Enable multiple input file for forward/reverse

### ISSUE THREAD

**Issue by apeltzer** [MikkelSchubert/adapterremoval#14]
It would be great if support for enabling multiple forward/reverse files could be added, e.g. instead of 
`--file1 fileX_R1 
  --file2 fileX_R2
`
One could have 
`
--file1 fileX_R1 fileY_R1 fileZ_R1
--file2 fileX_R2 fileY_R2 fileZ_R2
`
that would be great in various types of analysis procedures and shouldn't require much work to implement I guess. I already e-mailed you about that, just wanted to have something to follow up on / make this trackable for you as well. 

Thanks!

**Comment by MikkelSchubert** [comment]
Hi Alexander,
I was actually thinking about something like --file1 fileX_R1 --file1 fileY_R1 --file1 fileZ_R1 --file2 fileX_R2 --file2 fileY_R2 --file2 fileZ_R2. But I think that your solution is not only neater, but should also be easier to add based on my existing argument-parser code, so I'll go with what you suggest.

I hope to be able to work on this next week.

Cheers,
 Mikkel

**Comment by apeltzer** [comment]
Sounds good - no worries about the timing though!

**Comment by MikkelSchubert** [comment]
Support for multiple input files is now part of AdapterRemoval v2.2.1.

Based on your suggestion, the files are simply specified one after each other following the --file1 or --file2 option:

    $ AdapterRemoval --file1 reads_1a.fq reads_1b.fq reads_1c.fq
    $ AdapterRemoval --file1 reads_1a.fq reads_1b.fq reads_1c.fq --file2 reads_2a.fq reads_2b.fq reads_2c.fq

It should work entirely transparently (regardless of compression or lack thereof), but just let me know if you run into any issues.

Cheers,
 Mikkel
