### ISSUE TITLE
Missing <numeric> header include in fastq.cc

### ISSUE THREAD

**Issue by ilovezfs** [MikkelSchubert/adapterremoval#16]
The build fails on macOS (tested with 10.10, 10.11, and 10.12) with the following error:
```
src/fastq.cc:198:29: error: no member named 'accumulate' in namespace 'std'
    long running_sum = std::accumulate(m_qualities.begin(),
                       ~~~~~^
1 error generated.
```

See https://jenkins.brew.sh/job/Homebrew%20Science%20Pull%20Requests/410/version=sierra/console

It seems `#include <numeric>` is missing.

**Comment by ilovezfs** [comment]
Thanks!

**Comment by MikkelSchubert** [comment]
I'll have a new version out in a minute, and I've have added OSX to the travis build, so that hopefully this won't happen again. Thank you very much for letting me know!

Cheers,
 Mikkel

**Comment by ilovezfs** [comment]
No problem! I'll close https://github.com/Homebrew/homebrew-science/pull/5714 and await the new release. Thank you for rolling one.
