### ISSUE TITLE
Missing include statement

### ISSUE THREAD

**Issue by tillea** [MikkelSchubert/adapterremoval#17]
Hi,
please consider applying the following [patch](https://anonscm.debian.org/cgit/debian-med/adapterremoval.git/tree/debian/patches/add_missing_header.patch) which was needed to build version 2.2.1 under Debian when using gcc 6.
Kind regards, Andreas.

**Comment by MikkelSchubert** [comment]
Thank you.
I'll include that patch in the next release.

**Comment by MikkelSchubert** [comment]
This issue was fixed in 2.2.1a, but I forgot to close the issue.
Thanks again for the report and for the patch.
