### ISSUE TITLE
No sudo permission

### ISSUE THREAD

**Issue by kaigedong** [MikkelSchubert/adapterremoval#20]
I am very interested in the function `AdapterRemoval`, but I don't have the `sudo` permission. It's hard to install this software.Is there any plan to offer `pip` or `conda` installtation?

**Comment by MikkelSchubert** [comment]
Sudo permission is only needed if you want to install AdapterRemoval for all users. If you simply want to use the program yourself, then you can run the executable directly from the build directory (./build/AdapterRemoval) after you've run the 'make' command, or move it to a folder listed in your PATH variable. That is how I use the program myself.

I do not plan to offer pip (AdapterRemoval is not a Python program) or conda packages. If you need help installing AdapterRemoval on a shared system, then you should contact your system administrator.

Cheers

**Comment by nickjhathaway** [comment]
You can also install to another directory by setting PREFIX when running make 

```
make install PREFIX=/path/to/install/dir
```

**Comment by MikkelSchubert** [comment]
Conda packages are now available for AdapterRemoval thanks to several kind contributors. You can install AdapterRemoval as follows:

    conda install -c bioconda adapterremoval

or 

    conda install -c maxibor adapterremoval2

Feel free to open another issue if you have any further questions or if you run into any other problems.

Best,
 Mikkel
