### ISSUE TITLE
Conda installer

### ISSUE THREAD

**Issue by maxibor** [MikkelSchubert/adapterremoval#23]
I was facing some issues with installation of AdapterRemoval on different machines, so I created a conda package.
Available on anaconda cloud: [https://anaconda.org/maxibor/adapterremoval2](https://anaconda.org/maxibor/adapterremoval2)
Building source here: [https://github.com/maxibor/conda_recipes](https://github.com/maxibor/conda_recipes)
I can do a PR if needed

**Comment by MikkelSchubert** [comment]
Hi Maxime,
Thank you very much for creating this package!

However, I am afraid that I am not very familiar with Anaconda, so I'll have to read up on the specifics when I get the chance. Is there anything that you need me to do?

Cheers,
 Mikkel

**Comment by maxibor** [comment]
Hi Mikkel,
No nothing special, I can do a pull request if you want to integrate the conda installation instructions in the README.

Best,

**Comment by MikkelSchubert** [comment]
I'll gladly accept pull-requests.

Best,
 Mikkel

**Comment by maxibor** [comment]
#24

**Comment by MikkelSchubert** [comment]
Thanks!

**Comment by maxibor** [comment]
I updated the Travis tests for conda installation.
The build is now successful.

**Comment by MikkelSchubert** [comment]
Thank you, much appreciated.

Unfortunately I committed a fix just prior to your pull request. Your version of the build script also appears to remove the OSX/Clang builds, and doesn't run the test suite either. These both features of the CI build that I am keen on retaining, so I am not willing to merge this as is.
