### ISSUE TITLE
Bioconda package is there

### ISSUE THREAD

**Issue by apeltzer** [MikkelSchubert/adapterremoval#26]
Hi! 
just wanted to mention that there is a bioconda package available now for your tool (I sent a pull request to bioconda-recipes):  

` conda install -c bioconda adapterremoval `

Similar to that, there will be a corresponding docker image automatically available via the biocontainers project. You could mention this in the README, just to people can use it :-) 

Cheers,
Alex

**Comment by MikkelSchubert** [comment]
Thank you, much appreciated!
