### ISSUE TITLE
What means Length 0 in the read distribution field under the settings file report

### ISSUE THREAD

**Issue by VictorGoitea** [MikkelSchubert/adapterremoval#27]
Hello,

I would like to understand this minor detail of the report:

[Length distribution]
Length	Mate1	Discarded	All
0	0	92	92
1	0	0	0

I've just pasted 4 lines of the report. My reads length of sequencing was 50. For me would makes sense a scale from 1 to 50 but reads of length 0 what are they?

I couldn't fin this answer surfing the web, then I think you could make this clear please. Apologies if it is very stupid question.

Best,

Victor

**Comment by MikkelSchubert** [comment]
Hi Victor,

That is not a stupid question at all.
The length distribution is for the length of reads *after* AdapterRemoval
has trimmed adapter sequences and low-quality bases (if enabled), so a
length of zero means that AdapterRemoval has trimmed away the entire read.
This can happen in a couple of cases:

Firstly, if you have adapter dimers. That is to say if you have a pair of
adapters that are ligated to each other, with no template DNA in between.
In that case there'll be nothing left once you've removed the adapter
sequences. Secondly, if you have trimming of Ns and/or low-quality bases
enabled, then you sometimes run into reads where the entire read is of such
low quality that all of it gets trimmed. In my experience you pretty much
expect to see some of both of these types of reads even in high quality NGS
data sets.

Best regards,
 Mikkel
