### ISSUE TITLE
Adapter lists is interpreted differently compared to command line input

### ISSUE THREAD

**Issue by KarolisM** [MikkelSchubert/adapterremoval#31]
Hi,

It seems that AdapterRemoval is interpreting adapter sequences provided via command line and via file differently. In the first case adapter-1 and adapter-2 are parsed to the same sequences as user provides. In the second case with --adapter-list option adapter-2 is parsed to reverse complement. Is this expected behaviour? From user perspective I would say that it is not. 

Karolis

**Comment by MikkelSchubert** [comment]
Hi Karolis,

Thank you for the report!
That is indeed not the intended behaviour and I'll have an update out soon
to fix this.

Best,
Mikkel

**Comment by MikkelSchubert** [comment]
Thank you once again for this report.
I've released a new version of AdapterRemoval (v2.2.3) that fixes this, along with some other issues.

Best,
 Mikkel
