### ISSUE TITLE
--identify-adapters doesn't respect --mate-separator 

### ISSUE THREAD

**Issue by yonist** [MikkelSchubert/adapterremoval#34]
It seems that '--identify-adapters' doesn't respect --mate-separator the same way the remove code does (it might even ignore it altogether) 

> [nash]$ **/opt/adapterremoval/AdapterRemoval --basename test --file1 r1.100.fastq --file2 r2.100.fastq --mate-separator .**
> Trimming paired end reads ...
> Opening FASTQ file 'r1.100.fastq'
> Opening FASTQ file 'r2.100.fastq'
> Processed a total of 50 reads in 0.0s; 58,000 reads per second on average ...
> **[nash]$ /opt/adapterremoval/AdapterRemoval --identify-adapters --file1 r1.100.fastq --file2 r2.100.fastq --mate-separator .**
> Attempting to identify adapter sequences ...
> Opening FASTQ file 'r1.100.fastq'
> Opening FASTQ file 'r2.100.fastq'
> ERROR: Unhandled exception in thread:
>     Pair contains reads with mismatching names:
>     - 'SRR5275456.1.1'
>     - 'SRR5275456.1.2'

> Note that AdapterRemoval by determines the mate numbers as the digit found at the end of the read name, if this is preceded by the character '/'; if these data makes use of a different character to 
> separate the mate number from the read name, then you will need to set the --mate-separator command-line option to the appropriate character.
> 

Attached are the 2 files in the example above.

[r1.100.fastq.gz](https://github.com/MikkelSchubert/adapterremoval/files/2848835/r1.100.fastq.gz)
[r2.100.fastq.gz](https://github.com/MikkelSchubert/adapterremoval/files/2848836/r2.100.fastq.gz)

**Comment by MikkelSchubert** [comment]
Thank you very much for the report!

You are exactly right; the --identify-adapters option did not respect the --mate-seperator option. I've fixed this and released a new version of AdapterRemoval that includes this fix..

Best,
 Mikkel
