### ISSUE TITLE
Possible to uninstall/reinstall?

### ISSUE THREAD

**Issue by anthrograd20** [MikkelSchubert/adapterremoval#38]
Hello,

I am running Adapter Removal 2.2.2 through Qiime 1.9 on a Virtual Box setup (running most recent version VB 6.0)

Recently, when running AdapterRemoval at the beginning of my workflow, I get blank output_paired.collapsed.truncated files (sometimes blank output_paired.collapsed files as well). Previously, I was getting populated files. My raw data files have information in them, so I'm struggling to figure out where my issue is that would lead to blank files. 

I'm wondering if there is a way to uninstall AdapterRemoval and reinstall to be sure I have all the necessary components?

Thank you for your help!

Sarah

**Comment by MikkelSchubert** [comment]
Hi Sarah,

AdapterRemoval consists of a single, self-contained executable.
If you want to make sure that you have a clean install, then simply find
and delete any executable named "AdapterRemoval" (assuming that you haven't
renamed them).

The only other files included in the installation are documentation files
and example data, neither of which is referenced when AdapterRemoval is
executed.

However, if you are getting blank output files, then you should probably
check if AdapterRemoval is actually running to completion and if it is
printing any error messages to STDERR.

Best regards,
 Mikkel

**Comment by anthrograd20** [comment]
Hi Mikkel,

Thank you for your help previously. I followed your steps checking for error messages and doing a re-install of AdapterRemoval, but I am still experiencing the same issue.

AdapterRemoval runs to completion - and for instance, when I run one sample, I get this information:

(base) qiime@qiime-190-virtual-box:~/DecompTX/Fastq$ AdapterRemoval --file1 D61.16.R1.fastq.gz --file2 D61.16.R2.fastq.gz --basename output_paired --trimns --trimqualities --collapse
Trimming paired end reads ...
Opening FASTQ file 'D61.16.R1.fastq.gz'
Opening FASTQ file 'D61.16.R2.fastq.gz'
Processed a total of 42,396 reads in 0.5s; 91,000 reads per second on average ...

When I do a seqs count on each individual extracted file, R1 and R2 both show:
21198  : D61.16.R1.fastq (Sequence lengths (mean +/- std): 200.0000 +/- 0.0000)
21198  : Total

However, of the files written, only output_paired.collapsed (12.1MB), output_paired.pair1.truncated (138.7kB), output_paired.pair2.truncated (138.7kB), and output_paired.settings (8.3kB) have any information. No information was written to output_paired.collapsed.truncated. 

I am having this issue with almost every file, except for several where no information was written to either output_paired.collapsed or collapsed.truncated. My collaborator is not having this issue, which makes me think it's something to do with my computing setup rather than the data. 

I'm not sure what my next step is except to maybe reinstall everything all the way down to VirtualBox. 

If you have any insight, that would be much appreciated! Thank you for your time.

Sarah

**Comment by MikkelSchubert** [comment]
Hi Sarah,

I am sorry to hear that you are still having problems.

You say that your collaborator isn't having these issues.
Does that mean that both you and your collaborator have tried to process
the exact same files with AdapterRemoval?

Also, can you try attaching the .settings files for one of your problematic
runs?


However, I am wondering if there might have been a slight misunderstanding.
You wrote that "of the files written, only output_paired.collapsed
(12.1MB), output_paired.pair1.truncated (138.7kB),
output_paired.pair2.truncated (138.7kB), and output_paired.settings (8.3kB)
have any information. No information was written to
output_paired.collapsed.truncated."

These numbers look perfectly fine to me.
You have a lot of collapsed (merged) reads and a small number of reads that
weren't collapsed. What you don't have are reads that were collapsed and
then truncated by the quality-trimming, but the presense of those will
depend on the quality of your reads. Generally, the higher the quality, the
fewer collapsed.truncated and singleton reads you'll have.

If you also get a blank output.collapsed file, then that most likely
indicates that your DNA inserts were longer than 2 times your read length,
resulting in AdapterRemoval being unable to find any overlap between them.
In that case, you'll just get a lot of reads in pair1.truncated and
pair2.truncated. This is not unusual for modern DNA, depending on what kind
of DNA fragmentation was used during library preparation (if any).

Best,
 Mikkel
