### ISSUE TITLE
Support for interleaved PE reads?

### ISSUE THREAD

**Issue by tseemann** [MikkelSchubert/adapterremoval#4]
Is there any chance of interleaved PE reads being supported?

**Comment by MikkelSchubert** [comment]
Yes, I don't think that should be too hard to add, assuming that I've understood you correctly.

By interleaved PE reads, do you mean files containing both the mate 1 and mate 2 reads? E.g. read1/1, read1/2, read2/1, read2/2, etc. when read sequentially.

**Comment by MikkelSchubert** [comment]
Another question: Are you interested in AdapterRemoval reading interleaved reads and / or writing interleaved reads? I do not make use of this format myself, so it is not clear which is needed.
