### ISSUE TITLE
AdapterRemoval returning junk reads in paired1 and 2.truncated files

### ISSUE THREAD

**Issue by rmaustin** [MikkelSchubert/adapterremoval#43]
Hi,

I am having an issue with AdapterRemoval returning junk sequences in the paired1 and paired2.truncated files. 

AdapterRemoval v2.1.7.
code used - 

AdapterRemoval --threads 10 --file1 <(zcat SI325271_S1_R1.fastq.gz) --file2 <(zcat SI325271_S1_R2.fastq.gz) --minalignmentlength 10 --trimns --trimqualities --minquality 30 --collapse --minlength 25 --basename SI325271.30 --adapter1 AGATCGGAAGAGCACACGTGTGAACTCCAGTCACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG --adapter2 AGATCGGAAGAGCGTCGGTAGGGAAAGAGTGTTCTCTAGGGTGTAGATCTCGGTGGTCGCCGGATCATT

The junk reads are basically 150-bp reads containing long stretches of As or Ts. They are present in the output.paired1.truncated and output.paired2.truncated files, but do not make it past merging not in output.collapsed or output.collapsed.truncated. We see them regardless of using the --minquality 20 or 30 thresholds. 

Is there any insight you can provide concerning this issue?

**Comment by MikkelSchubert** [comment]
Hi,

It is not clear from your message, but are these reads introduced by
AdapterRemoval or are they reads that are also found in your input files?
AdapterRemoval currently does not perform filtering of low-complexity
reads, so if the quality of the bases in the junk reads are high (meaning
that little or no --trimquality trimming takes place), then the reads will
not be filtered by the --minlength option.

It would be helpful if you could copy/paste a couple of examples of such
reads, before and after trimming.
Alternatively, if the data you are trying to process is publicly available,
then you can just tell me where I can find it.

Cheers,
 Mikkel

**Comment by MikkelSchubert** [comment]
Closing due to lack of response.
