### ISSUE TITLE
collapse with SE reads

### ISSUE THREAD

**Issue by fgvieira** [MikkelSchubert/adapterremoval#55]
Not sure I understand what the `collapse` option does with SE reads.

In the manpage says that `collapse`, in SE mode, attempts `[...] to identify templates for which the entire sequence is available.`
and on the collapsed output, it says :
`[...] reads for which the adapter was identified by a minimum overlap, indicating that the entire template molecule is present.`

But what do templates refer to? Is it reads that contain adapters?
If so, has the adapter been trimmed? And why are these reads not included in the normal output?
If not, what are these SE reads that are "collapsed"?

**Comment by MikkelSchubert** [comment]
The idea was that this option would separate out reads for which you could be reasonably sure that you had the entire DNA insert, by virtue of having securely identified the adapter sequence using the same minimum overlap as when merging PE reads. Such reads could potentially be filtered for PCR duplicates the same way that merged reads can be filtered (e.g. with `paleomix rmdup_collpased`) which should lead to fewer false positive PCR duplicate labels.

However, I don't know if anyone ever used this. We certainly never got around to doing so and paleomix doesn't use this option either. As a consequence, this option has already been removed in my local branch, where I am working on more easily understood trimming statistics, along with a number of other breaking changes.

Cheers,
Mikkel

**Comment by fgvieira** [comment]
Hi Mikkel,

thanks for the quick reply.
Can I assume then that this option will be dropped from future versions of `AdapterRemoval`?

**Comment by MikkelSchubert** [comment]
That is correct.
