### ISSUE TITLE
combine with other QC tools

### ISSUE THREAD

**Issue by binlu1981** [MikkelSchubert/adapterremoval#60]
Hi Mikkel,

Do I need to run other QC tools (Trimmomatic, fastp,  et. al) before or after the Adapterremoval if I also want to trim poor quality reads and bases at the both end.

Best 
Bin

**Comment by MikkelSchubert** [comment]
Hi Bin,

AdapterRemoval provides a few options to trim low-quality bases (`--trimqualities`, `--trimns`, etc.). These trim both ends of the reads, unless trimming of the 5p end is explicitly disabled with the `--preserve5p` option.

See the manual for more information:
https://adapterremoval.readthedocs.io/en/stable/manpage.html#fastq-trimming-options

Best,
Mikkel
