### ISSUE TITLE
New version of catch.hpp needed for glibc >= 2.34

### ISSUE THREAD

**Issue by tillea** [MikkelSchubert/adapterremoval#63]
Hi,
as you can see in a [Debian bug report](https://bugs.debian.org/1009616) you should upgrade catch.hpp to a more recent version.
Kind regards, Andreas.

**Comment by MikkelSchubert** [comment]
Hi Andreas,

This has been fixed in master for a while, but I didn't think to roll a new release since it only affected the tests.
That has been done now (v2.3.3).

Best,
Mikkel
