### ISSUE TITLE
support .gz format fastq as input

### ISSUE THREAD

**Issue by junjunlab** [MikkelSchubert/adapterremoval#65]
Hi, thanks for this great package. Can this tool accept .gz compressed format fastq file as input? Maybe it is usefull.

**Comment by MikkelSchubert** [comment]
AdapterRemoval supports both reading and writing gzip compressed files.
Compressed input files are automatically detected and decompressed, while gzip

Version 2.x also supports bzip2 compression, but that is slated for removal in version 3.x.
