### ISSUE TITLE
Issue with out of range FASTQ qualities 

### ISSUE THREAD

**Issue by vsbuffalo** [MikkelSchubert/adapterremoval#71]
Hello,

I am trying to use AdapterRemoval to ensure reads downloaded from the SRA don't have any aberrant adapters. However I am having issues with AdapterRemoval. 

I have included `in.fq.gz` as a small test file. When I run the follow I get an error (version included for reference):

```
❯ adapterremoval --version
AdapterRemoval ver. 2.3.4

❯ adapterremoval --file1 in.fq.gz --output1 out.fq.gz --qualitybase 33 --gzip
Trimming single ended reads ...
Opening FASTQ file 'in.fq.gz', line numbers start at 1
Error reading FASTQ record at line 9; aborting:
    Phred+33 encoded quality score is greater than the expected maximum of 41 (J). Please verify the format of these files.

    If the quality scores are actually Phred+64 encoded, then use the '--qualitybase 64' command-line option.

    If the quality scores are Phred+33 encoded, but includes scores in a greater range than expected, then use the '--qualitymax' option. Note that this option effects both reading and writing of FASTQ files.

    See README for more information.
Aborting thread due to error.
ERROR: AdapterRemoval did not run to completion;
       do NOT make use of resulting trimmed reads!
```

FASTQC indicates that this file has encoding Sanger / Illumina 1.9. I wrote a simple script (attached) that produces the following histogram of quality scores characters: 

```
❯ python quality.py in.fq.gz
ASCII 34 ('"'): 34
ASCII 35 ('#'): 1
ASCII 40 ('('): 4
ASCII 41 (')'): 2
ASCII 42 ('*'): 12
ASCII 43 ('+'): 16
ASCII 44 (','): 23
ASCII 45 ('-'): 9
ASCII 46 ('.'): 12
ASCII 47 ('/'): 7
ASCII 48 ('0'): 9
ASCII 49 ('1'): 5
ASCII 50 ('2'): 10
ASCII 51 ('3'): 9
ASCII 52 ('4'): 17
ASCII 53 ('5'): 15
ASCII 54 ('6'): 24
ASCII 55 ('7'): 34
ASCII 56 ('8'): 76
ASCII 57 ('9'): 72
ASCII 58 (':'): 137
ASCII 59 (';'): 205
ASCII 60 ('<'): 313
ASCII 61 ('='): 462
ASCII 62 ('>'): 1,239
ASCII 63 ('?'): 3,599
ASCII 64 ('@'): 6,335
ASCII 65 ('A'): 11,661
ASCII 66 ('B'): 14,542
ASCII 67 ('C'): 5,525
ASCII 68 ('D'): 1,706
ASCII 69 ('E'): 832
ASCII 70 ('F'): 350
ASCII 71 ('G'): 149
ASCII 72 ('H'): 60
ASCII 73 ('I'): 35
ASCII 74 ('J'): 12
ASCII 75 ('K'): 23
ASCII 76 ('L'): 1
ASCII 77 ('M'): 7
ASCII 78 ('N'): 12
ASCII 79 ('O'): 5
ASCII 80 ('P'): 20
ASCII 81 ('Q'): 22
ASCII 82 ('R'): 27
ASCII 83 ('S'): 13
ASCII 84 ('T'): 8
ASCII 85 ('U'): 9
ASCII 86 ('V'): 13
ASCII 87 ('W'): 19
ASCII 88 ('X'): 16
ASCII 89 ('Y'): 14
ASCII 90 ('Z'): 10
ASCII 91 ('['): 3
ASCII 92 ('\'): 4
ASCII 93 (']'): 3
ASCII 94 ('^'): 4
ASCII 95 ('_'): 2
ASCII 96 ('`'): 3
ASCII 99 ('c'): 2
ASCII 101 ('e'): 1
ASCII 103 ('g'): 1
ASCII 106 ('j'): 1
ASCII 107 ('k'): 1
ASCII 108 ('l'): 1
ASCII 109 ('m'): 1
ASCII 110 ('n'): 3
ASCII 112 ('p'): 2
ASCII 113 ('q'): 1
ASCII 116 ('t'): 2
ASCII 117 ('u'): 1
ASCII 119 ('w'): 1
ASCII 120 ('x'): 1
ASCII 121 ('y'): 1
ASCII 122 ('z'): 1
ASCII 123 ('{'): 1
ASCII 125 ('}'): 1
ASCII 126 ('~'): 1
```

Which indicates the max is 126. When I try to use that though, I get an error:

```
❯ adapterremoval --file1 in.fq.gz --output1 out.fq.gz --qualitybase 33 --qualitymax 126 --gzip
libc++abi: terminating due to uncaught exception of type std::invalid_argument: ASCII value cutoff for quality scores lies after printable characters
zsh: abort      adapterremoval --file1 in.fq.gz --output1 out.fq.gz --qualitybase 33  126
```

As far as I know `~` (ASCII 126) is a valid quality character for PHRED+33, so I am stumped why this won't work. 

Any ideas what is going on here? My apologies if this is something simple I am overlooking. 

[in.fq.gz](https://github.com/user-attachments/files/17501871/in.fq.gz)

[quality.py.gz](https://github.com/user-attachments/files/17502038/quality.py.gz)

**Comment by MikkelSchubert** [comment]
Hi,

The problem is that you are specifying the ASCII value of a Phred+33 encoded score (in the range 33 to 126), whereas AdapterRemoval is expecting a plain Phred score (in the range 0 to 93). So `--qualitymax 93` should do what you want.

I can see that the error message and help text are somewhat ambiguous, so I'll try to improve them:

    --qualitymax BASE
        Specifies the maximum Phred score expected in input files, and used
        when writing output. ASCII encoded values are limited to the
        characters '!' (ASCII = 33) to '~' (ASCII = 126), meaning that
        possible scores are 0 - 93 with offset 33, and 0 - 62 for offset 64
        and Solexa scores [default: 41].


Best,
Mikkel

**Comment by vsbuffalo** [comment]
Ah, I see — thanks for the clarification. My apologies for overlooking this detail. I do think a more informative error message would be helpful.
